### ISSUE TITLE
Next.js not loading environment variables in browsers 

### ISSUE THREAD

**Issue by witoszekdev** [saleor/saleor-checkout#171]
## Steps to reproduce the problem
1. Make sure env variables are defined in `.env.local` or in the root of monorepo in `.env`
2. Run `saleor-app-checkout` on main brach with `pnpm run dev`
3. Visit the app at `localhost:3000`

## Current result
`NEXT_PUBLIC_SALEOR_API_URL` is not exposed to the client: `undefined` in browser, OK in node.

## Expected behavior
`NEXT_PUBLIC_*` variables are loaded correctly in browsers

### System:
 - OS: macOS 12.4
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
 - Memory: 174.21 MB / 16.00 GB
 - Shell: 5.8.1 - /bin/zsh
### Binaries:
 - Node: 18.2.0 - /usr/local/bin/node
 - Yarn: 1.22.18 - /usr/local/bin/yarn
 - npm: 8.9.0 - /usr/local/bin/npm
 - Watchman: 2022.05.16.00 - /usr/local/bin/watchman
 - pnpm: 7.5.2
### Browsers:
 - Brave Browser: 103.1.40.113
 - Chrome: 103.0.5060.134
 - Firefox Developer Edition: 101.0
 - Safari: 15.5

**Comment by witoszekdev** [comment]
It's not fully fixed yet, see this: https://github.com/saleor/saleor-checkout/pull/174#issuecomment-1195526709

**Comment by mmiszy** [comment]
This is a different problem, let's track it in https://github.com/saleor/saleor-checkout/issues/187
