### ISSUE TITLE
ERROR turbo run build failed

### ISSUE THREAD

**Issue by chrislais** [saleor/saleor-checkout#92]
The following error occurs in some cases, such as building an image using git submodule in docker, and the ERROR disappeared after I used **"turbo": "1.2.4"**

#https://github.com/vercel/turborepo/issues/1257

 => ERROR [15/15] RUN pnpm run build                                                                                                      0.8s 
------
 > [15/15] RUN pnpm run build:
#19 0.801
#19 0.801 > turborepo-basic-shared@0.0.0 build /checkout
#19 0.801 > turbo run build
#19 0.801
#19 0.821  ERROR  failed to calculate global hash: error hashing files. make sure that git has been initialized failed to hash files /checkout/pnpm-lock.yaml, /checkout/package.json: git hash-object exited with status: exit status 128. Output:
#19 0.821 fatal: Not a git repository: ../.git/modules/checkout
#19 0.821
#19 0.824  ELIFECYCLE  Command failed with exit code 1.
------
executor failed running [/bin/sh -c pnpm run build]: exit code: 1
ERROR: Service 'checkout' failed to build : Build failed

**Comment by timuric** [comment]
@chrislais is this still an issue? We are using the latest turbo version in ```package.json```
