### ISSUE TITLE
Unable to checkout

### ISSUE THREAD

**Issue by blackyzero** [saleor/saleor-checkout#99]
Hello,

I am getting following error from console when trying to checkout.

`checkout:dev:   ../../node_modules/.pnpm/css-loader@6.7.1_webpack@5.72.0/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!../../node_modules/.pnpm/postcss-loader@6.2.1_ophkbroklgd6jdvupnp5h6xq4i/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!../../node_modules/.pnpm/source-map-loader@3.0.1_webpack@5.72.0/node_modules/source-map-loader/dist/cjs.js!./src/index.css 26.3 KiB [built]
checkout:dev:   ../../packages/ui-kit/dist/esm/index.js 79 KiB [built]
checkout:dev: webpack 5.72.0 compiled successfully in 2568 ms
checkout:dev: No issues found.
checkout-app:dev: wait  - compiling /channels (client and server)...
checkout-app:dev: wait  - compiling...
checkout-app:dev: event - compiled client and server successfully in 2.6s (953 modules)
checkout-app:dev: Material-UI: The `fade` color utility was renamed to `alpha` to better describe its functionality.
checkout-app:dev:
checkout-app:dev: You should use `import { alpha } from '@material-ui/core/styles'`
checkout-app:dev: Material-UI: the createMuiTheme function was renamed to createTheme.
checkout-app:dev:
checkout-app:dev: You should use `import { createTheme } from '@material-ui/core/styles'`
checkout-app:dev: wait  - compiling /_error (client and server)...
checkout-app:dev: wait  - compiling...
checkout-app:dev: event - compiled client and server successfully in 1081 ms (954 modules)`

When trying to access the checkout page manually, i get following error (screenshot)
<img width="2198" alt="Screen Shot 2022-06-04 at 10 48 29 AM" src="https://user-images.githubusercontent.com/4286063/172008520-4ead52a2-90a4-432a-ad30-de5c346483e1.png">

To reproduce issue
- Clone and install checkout repo
- start dev mode
- checkout any product from storefront.

Is there anyway to fix it?
Thank you.

**Comment by timuric** [comment]
@blackyzero we have updated the checkout project with a new readme and Saleor demo storefront is using the new checkout project as well. Please take a look https://github.com/saleor/saleor-checkout

**Comment by blackyzero** [comment]
Great. I will try it very soon. Thanks @timuric for those updates.
